name: Update Helm Image Tag
on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Short commit hash for image tag'
        required: true
        type: string
jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update image tag in Helm values.yaml
        run: |
          sed -i "s/tag: .*/tag: ${{ github.event.inputs.commit_hash }}/" manifests/helm/values.yaml
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add manifests/helm/values.yaml
          git commit -m "Update image tag to ${{ github.event.inputs.commit_hash }}"
          git push
