name: Terraform Apply
on:
  workflow_dispatch
#  push:
#    paths:
#      - 'terraform/**'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform -chdir=terraform init
      - name: Terraform Plan
        run: terraform -chdir=terraform plan
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
